/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erp.viji.gui;

/**
 *
 * @author Javier
 */
public class JPLogin extends javax.swing.JPanel {

    /**
     * Creates new form JPLogin
     */
    public JPLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Usuario:");
        add(jLabel1);
        jLabel1.setBounds(80, 120, 70, 19);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Contraseña:");
        add(jLabel2);
        jLabel2.setBounds(70, 170, 85, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Login");
        add(jLabel3);
        jLabel3.setBounds(210, 30, 100, 40);
        add(jTextField2);
        jTextField2.setBounds(170, 110, 229, 30);
        add(jPasswordField1);
        jPasswordField1.setBounds(170, 160, 230, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erp/viji/resources/palomitas - 100x100.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(150, 210, 110, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erp/viji/resources/viji 100x100.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(240, 270, 110, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
