/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erp.viji.gui;

/**
 *
 * @author Javier
 */
public class JPViji extends javax.swing.JPanel {

    /**
     * Creates new form JPViji
     */
    public JPViji() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPCines = new javax.swing.JPanel();
        JPClientes = new javax.swing.JPanel();
        JPProveedores = new javax.swing.JPanel();
        JPEmpleados = new javax.swing.JPanel();
        JPProductos = new javax.swing.JPanel();
        JPReservas = new javax.swing.JPanel();
        JPPeliculas = new javax.swing.JPanel();
        JPSesiones = new javax.swing.JPanel();
        JPEntradas = new javax.swing.JPanel();
        JPUsuarios = new javax.swing.JPanel();
        JPPedidos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 204));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        JPCines.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout JPCinesLayout = new javax.swing.GroupLayout(JPCines);
        JPCines.setLayout(JPCinesLayout);
        JPCinesLayout.setHorizontalGroup(
            JPCinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        JPCinesLayout.setVerticalGroup(
            JPCinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cines", JPCines);

        JPClientes.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout JPClientesLayout = new javax.swing.GroupLayout(JPClientes);
        JPClientes.setLayout(JPClientesLayout);
        JPClientesLayout.setHorizontalGroup(
            JPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        JPClientesLayout.setVerticalGroup(
            JPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Clientes", JPClientes);

        JPProveedores.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout JPProveedoresLayout = new javax.swing.GroupLayout(JPProveedores);
        JPProveedores.setLayout(JPProveedoresLayout);
        JPProveedoresLayout.setHorizontalGroup(
            JPProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        JPProveedoresLayout.setVerticalGroup(
            JPProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Proveedores", JPProveedores);

        JPEmpleados.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout JPEmpleadosLayout = new javax.swing.GroupLayout(JPEmpleados);
        JPEmpleados.setLayout(JPEmpleadosLayout);
        JPEmpleadosLayout.setHorizontalGroup(
            JPEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        JPEmpleadosLayout.setVerticalGroup(
            JPEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Empleados", JPEmpleados);

        JPProductos.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout JPProductosLayout = new javax.swing.GroupLayout(JPProductos);
        JPProductos.setLayout(JPProductosLayout);
        JPProductosLayout.setHorizontalGroup(
            JPProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        JPProductosLayout.setVerticalGroup(
            JPProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Productos", JPProductos);

        JPReservas.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout JPReservasLayout = new javax.swing.GroupLayout(JPReservas);
        JPReservas.setLayout(JPReservasLayout);
        JPReservasLayout.setHorizontalGroup(
            JPReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        JPReservasLayout.setVerticalGroup(
            JPReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reservas", JPReservas);

        JPPeliculas.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout JPPeliculasLayout = new javax.swing.GroupLayout(JPPeliculas);
        JPPeliculas.setLayout(JPPeliculasLayout);
        JPPeliculasLayout.setHorizontalGroup(
            JPPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        JPPeliculasLayout.setVerticalGroup(
            JPPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Películas", JPPeliculas);

        JPSesiones.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout JPSesionesLayout = new javax.swing.GroupLayout(JPSesiones);
        JPSesiones.setLayout(JPSesionesLayout);
        JPSesionesLayout.setHorizontalGroup(
            JPSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        JPSesionesLayout.setVerticalGroup(
            JPSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sesiones", JPSesiones);

        JPEntradas.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout JPEntradasLayout = new javax.swing.GroupLayout(JPEntradas);
        JPEntradas.setLayout(JPEntradasLayout);
        JPEntradasLayout.setHorizontalGroup(
            JPEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        JPEntradasLayout.setVerticalGroup(
            JPEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Entradas", JPEntradas);

        JPUsuarios.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout JPUsuariosLayout = new javax.swing.GroupLayout(JPUsuarios);
        JPUsuarios.setLayout(JPUsuariosLayout);
        JPUsuariosLayout.setHorizontalGroup(
            JPUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        JPUsuariosLayout.setVerticalGroup(
            JPUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Usuarios", JPUsuarios);

        JPPedidos.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout JPPedidosLayout = new javax.swing.GroupLayout(JPPedidos);
        JPPedidos.setLayout(JPPedidosLayout);
        JPPedidosLayout.setHorizontalGroup(
            JPPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        JPPedidosLayout.setVerticalGroup(
            JPPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pedidos", JPPedidos);

        add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 128, 570, 340);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erp/viji/resources/viji 100x100.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(80, 70, 110, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/erp/viji/resources/palomitas - 100x100.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 10, 100, 100);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPCines;
    private javax.swing.JPanel JPClientes;
    private javax.swing.JPanel JPEmpleados;
    private javax.swing.JPanel JPEntradas;
    private javax.swing.JPanel JPPedidos;
    private javax.swing.JPanel JPPeliculas;
    private javax.swing.JPanel JPProductos;
    private javax.swing.JPanel JPProveedores;
    private javax.swing.JPanel JPReservas;
    private javax.swing.JPanel JPSesiones;
    private javax.swing.JPanel JPUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
